# postgres
version: '3'
services:
  gift_go_test_db:
    image: postgres:14.12
    container_name: gift_go_test_db
    environment:
      - POSTGRES_USER=gift-go-user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=assessment
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres:
    driver: local

networks:
  backend:
    driver: bridge